site_name: Hexapode
repo_url: https://github.com/NickVanMarkes/Hexapode
repo_name: NickVanMarkes/Hexapode
nav:
  - index.md
  - Introduction : abstract.md
  - Cahier des charges: CDC.md
  - Documentation technique:
      - Introduction.md
      - Planning: Plannification.md
      - Gestion du projet: Gestion.md
      - Structure : Structure.md
      # - Analyse fonctionnelle: technique/functionnal-analysis.md
      # - Analyse organique: technique/organic-analysis.md
      - Composants : Composants.md
      - Protocoles : Protocoles.md
      - Librairies : Librairies.md
      - Fonctionalitées : Fonctionalite.md
      - Tests: Tests.md
      - Difficultés: Difficulte.md
      - Conclusion: Conclusion.md
  - Annexes : 
    - Manuel utilisateur : man_utilisateur.md
    - Manuel d'installation : man_installation.md
    - Journal de bord : JDB.md
    - Code Source : 
      - Animations_Hexapode.md
      - Camera.md
      - Gyroscope.md
      - Leg.md
      - LidarAsync.md
      - Motor.md
      - Plot.md
      - RepeatTimer.md
      - Main.md
theme:
  name: material
  language: fr
  palette:
    primary: black
    accent: black
    scheme: slate
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.indexes
    - navigation.top
    - navigation.tabs
    - toc.integrate
watch:
  - app
  - app/mod_classes
plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [./app]
    
  - with-pdf:
      author: Nicolas Oliveira
      copyright: 2021-2022 cfpt
      #
      #cover: false
      #back_cover: true
      cover_title: Travail de diplôme
      cover_subtitle: Documentation Interface Flask
      cover_logo: "./images/logo.png"
      #custom_template_path: TEMPLATES PAT
      #
      toc_title: Table des matières
      #heading_shift: false
      #toc_level: 3
      #ordered_chapter_level: 2
      #excludes_children:
      #    - 'release-notes/:upgrading'
      #    - 'release-notes/:changelog'
      #
      #exclude_pages:
      #    - 'bugs/'
      #    - 'appendix/contribute/'
      #convert_iframe:
      #    - src: IFRAME SRC
      #      img: POSTER IMAGE URL
      #      text: ALTERNATE TEXT
      #    - src: ...
      #two_columns_level: 3
      #
      # render_js: true
      # headless_chrome_path: headless-chromium
      #
      #output_path: any-place/document.pdf
      #enabled_if_env: ENABLE_PDF_EXPORT
      #
      #debug_html: true
      #show_anchors: true
      #verbose: true
markdown_extensions:
  - attr_list
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.saneheaders
  - admonition
  - pymdownx.keys
  - pymdownx.caret
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.tasklist
  - pymdownx.tilde
  - pymdownx.superfences:
      # custom_fences:
      #   - name: mermaid
      #     class: mermaid
      #     format: !!python/name:mermaid2.fence_mermaid
      #     # format: !!python/name:pymdownx.superfences.fence_code_format
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
